### ISSUE TITLE
fix: Improve detection of degraded APIConnectCluster in Cloud Pak for Integration

### ISSUE THREAD

**Issue by nastacio** [IBM/cloudpak-gitops#253]
**Describe the bug**
APIConnectCluster is not marked as Degraded if a condition reports Pending=True and Reason=error, like this:

```
    - lastTransitionTime: '2023-06-21T13:17:49Z'
      message: >-
        an error occured while running job kr-two/apis-minimum-configurator.
        APIC installation in progress
      reason: Error
      status: 'True'
      type: Pending
```

We noticed this condition sometimes happens even if as the "Error" condition does not get set to True.

**To Reproduce**
N/A

**Expected behavior**
APIConnectCluster should be marked as Degraded if a condition reports Pending=True and Reason=error.

**Screenshots**

**Additional context**

```
status:
  conditions:
    - lastTransitionTime: '2023-06-21T13:16:44Z'
      message: ''
      reason: na
      status: 'False'
      type: Warning
    - lastTransitionTime: '2023-06-21T13:16:44Z'
      message: ''
      reason: na
      status: 'False'
      type: Ready
    - lastTransitionTime: '2023-06-21T13:17:49Z'
      message: >-
        an error occured while running job kr-two/apis-minimum-configurator.
        APIC installation in progress
      reason: Error
      status: 'True'
      type: Pending
```
