### ISSUE TITLE
RHACM 2.9 subscription channel no longer available in `redhat-operators` catalog

### ISSUE THREAD

**Issue by nastacio** [IBM/cloudpak-gitops#299]
**Describe the bug**

I tried to apply the recent changes made to the repo in feature #298 on a new cluster using OCP 4.12 and then on a new cluster using OCP 4.13.

Deployments worked on Wednesday (11/22) without any problems. However, starting a couple days later, either on Friday or Saturday (11/24 or 11/25,) the subscription on both clusters generated an alert about the subscription channel `release-2.9` no longer being available in the `redhat-operators` catalog source (see below.)

On a related note, and maybe that is just a coincidence, [Red Hat container registry suffered an outage](https://status.redhat.com/incidents/8ly6n3bp0s2h) on 11/25 and I wonder if the reinstatement of some images may have restored an older or corrupted version of the catalog source.

```yml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: release-2.9
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status:
  catalogHealth:
   ...
    - catalogSourceRef:
        apiVersion: operators.coreos.com/v1alpha1
        kind: CatalogSource
        name: redhat-operators
        namespace: openshift-marketplace
      healthy: true
  conditions:
    - lastTransitionTime: '2023-11-26T14:11:26Z'
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: 'False'
      type: CatalogSourcesUnhealthy
    - message: >-
        constraints not satisfiable: no operators found in channel release-2.9
        of package advanced-cluster-management in the catalog referenced by
        subscription advanced-cluster-management, subscription
        advanced-cluster-management exists
      reason: ConstraintsNotSatisfiable
      status: 'True'
      type: ResolutionFailed
```

**To Reproduce**
In order to simplify the troubleshooting, you can validate this issue directly in the OCP console, based on the [RHACM 2.9 instructions](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.9/html/install/installing)

1. Apply the Subscription YAML below to any OCP cluster on versions 4.12 or 4.13 (I have not tried it with 4.14 yet)
2. Wait for the `status.conditions` field to report the error about the `constraints not satisfiable`

```yml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: release-2.9
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```

**Expected behavior**
The Subscription should work and the operator should deploy without issue.

**Screenshots**

**Additional context**
On a 4.13 cluster:

<img width="1727" alt="image" src="https://github.com/IBM/cloudpak-gitops/assets/3278623/97537f74-6394-4333-a61a-241194342545">
